# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

# how the wkf will be triggred
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env: 
  DOKER_USER: "massipssa"
  DOKER_REPO: "devs"
  IMAGE_TAG: "workspace"
jobs:
  # job name (it can be customized)
  build-jar:
    # the machine in github that will run the job
    runs-on: ubuntu-latest
    
    # a command that can run an action or a command
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: print secret
      run: echo  ${{ secrets.hello }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [build-jar]
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -t "${{ env.DOKER_USER }}/${{ env.DOKER_REPO }}:${{ env.IMAGE_TAG }}" .